#!/usr/bin/perl

use strict;
use warnings;

package Main;

use Getopt::Std;

use lib '../lib';

use Plack::Runner;

sub main {
    my %opts;
    getopts('c:', \%opts);

    require MusicCircle::Config;
    MusicCircle::Config::load_config($opts{c});

    require MusicCircle::Data;
    MusicCircle::Data::connect();

    require MusicCircle::API;
    my $runner = Plack::Runner->new;
    $runner->set_options(%{ $MusicCircle::Config::options->{server} });
    $runner->run($MusicCircle::API::mc);
}

main;
