#!/usr/bin/perl

use strict;
use warnings;

package Main;

use Getopt::Std;

use lib '../lib';

use MusicCircle::Config;
use MusicCircle::API;
use MusicCircle::Data;

use Plack::Runner;

sub main {
    my %opts;
    getopts('c:', \%opts);

    MusicCircle::Config::load_config $opts{c};
    MusicCircle::Data::connect();

    my $runner = Plack::Runner->new;
    $runner->set_options(%{ $MusicCircle::Config::options->{server} });
    $runner->run($MusicCircle::API::mc);
}

main;
